# -*- coding: utf-8 -*-
"""Include her project Vidhi Saxena.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AOiU9SilIk7mLAgbBEWFfKh31R6gAuZS
"""

pip install OpenAI

api_key1="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"

"""#This section helps us in mun research"""

from openai import OpenAI
client=OpenAI(
    api_key=api_key1
)
response=client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role":"system",
            "content":"you are a united nations assistant your job is to give detailed information about the given agenda with respect to the given committee and the stance of given country on the same agenda "
        },
        {
            "role":"user",
            "content":"Tell me about Isreal and Palenstine conflict in UNSC and Australia's stance on it."
        },
        {
            "role":"assistant",
            "content":"The Israel-Palestine conflict revolves around the historical and ongoing disputes between Israelis and Palestinians over territory, national identity, and sovereignty. The conflict has deep-rooted historical, cultural, and political dimensions."
        },
    ]
)

assistant=response.choices[0].message.content

assistant

from openai import OpenAI
client=OpenAI(
    api_key=api_key1
)
response=client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role":"system",
            "content":"you are a united nations assistant your job is to give detailed information about the given agenda with respect to the given committee and the stance of given country on the same agenda "
        },
        {
            "role":"user",
            "content":"Tell me about Reviewing the working of the Office for project serviceswith emphasis on increasing accountability and transparency in operations in UNOPS and Norway's stance on it."
        },
        {
            "role":"assistant",
            "content":"The Office for Project Services (UNOPS) is a UN organization that provides project management, procurement, and infrastructure services to help implement sustainable development projects around the world. It plays a crucial role in supporting various UN agencies, governments, and other partners in delivering effective projects and programs."
        },
    ]
)

response.choices[0].message.content

"""#This section presents us with the option of transcripting verbatim of mun speeches for ease of records and marking."""

from openai import OpenAI
client = OpenAI(
    api_key="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"
)
audio_file= open("/content/Recording (4).m4a", "rb")
transcript = client.audio.transcriptions.create(
  model="whisper-1",
  file= audio_file,
  response_format="text"
)

transcript

from openai import OpenAI
client = OpenAI(
    api_key="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"
)
audio_file= open("/content/Recording (2).m4a", "rb")
transcript = client.audio.transcriptions.create(
  model="whisper-1",
  file= audio_file,
  response_format="text"
)

transcript

"""# Ideas and inspirations for caricaturists"""

from openai import OpenAI
client = OpenAI(
    api_key= api_key1
)

response = client.images.generate(
  model="dall-e-3",
  prompt="women of all ethnicities protecting for their rights against the backdrop of world ",
  size="1024x1024",
  quality="standard",
  n=1,
)

image_url = response.data[0].url

image_url

from openai import OpenAI
client = OpenAI(
    api_key= api_key1
)

response = client.images.generate(
  model="dall-e-3",
  prompt="a fairytale world of music ",
  size="1024x1024",
  quality="hd",
  n=1,
)

image_url = response.data[0].url

image_url